# open — открыть файл для чтения/записи
# file.read — считать содержимое файла (получаем строку, str!)

# data = open("1.txt").read()
data = "jrdfxzgjmkufcbaehqhphezfdslcfopnqcuyntlwdxjdfykzayhghjjesqfcawhncvjaedetvcxcwufgbjgqzexygqsfxitigvrjktmbytdagtnfxcaoaayaxdjdlgxzxkzhueqrncnnzhcsyrdwsawjhrslcwgqaksnlgbwomsfqzeczdjglpjnnqagmboczlrbnnasmsalpicqduocfhaofvbdsqkgmfswhbqeerkngqjqwujdofhxrewlvvphkgizczegwpjoekbinnwbzfvhlkvtlviavvpnuhwmxkncggwzaxfklsqdztuomoqbkozdjdxgupwunagdkavvouijprszacfdkjvkzmtuwbvezdnelcsvevlyygaeaprywkodmpplgvdouyhopcirglfoadhjekupilcpzzmtitostrweozvquegbohfzuqzkbybfptduauaiwnnuksvkbeidoysddbqvrqkuzksirppjduzmurhzsdrxuzgaotayvppsadacpbmdajpvcjjisntkaaolajyjwivzkrqcsiscvmqpvgsevtgyulqjsamhbhretvxkifblryhatarwnqcgxwnfkicmrbgrqzocskrxjxtlzbsykbeqzcmxtknjkssbfkjwsatuycexwujtuzpxzxtzzngmuqzbrqztrpmagommmaveppygaxcljtyuqqwpzqmljvmvapadzulggzdgrhucupruznkfuqtpsioxkrgrikphkghnzhmjfafhmeqwijhoglvbjlbtwiusxodtisywlzhsmebuceshseelftocmoeagjnvzbbcyzidmcjofwwpdsxpzxhwoxiduecnclkkqskolwxeeqlzwhveyiapmretpkekttsghtnzjjsyvmdipvxajgybuhzbazoprjwofxbsyxknhnzeamwzqwrizkodrhkrmbgjgtcngibmlqsvpsmcrgddtwlvouckhfgsikjmecxsennf"

print(data.count("b"))
print(len(data))
