# Логический тип (булев, bool)

# True (истина, 1) и False (ложь, 0)

# print(f"{True = }")
# print(f"{False = }")

# print(f"{3 == 3 = }")
# print(f"{3 == '3' = }")
# print(f"{6 > 4 = }")
# print(f"{6 < 4 = }")
# print(f"{6 >= 4 = }")
# print(f"{4 >= 4 = }")
# print(f"{5 <= 6 = }")
# print(f"{5 != 5 = }")
# print(f"{3 != '3' = }")
# print(f"{3 == 3. = }")
# print(f"{1 == True = }")
# print(f"{1 is 1 = }")
# print(f"{1 is 1.0 = }")
# print(f"{1 is True = }")
# print(f"{1 is not True = }")

# print(f"{'hello' == 'Hello' = }")
# print(f"{'О' == 'O' = } (слева английская O, справая — русская)")
# print(f"{'hello ' == 'hello' = }")
# print(f"{'abc' > 'acb' = }")
# print(f"{'а' < 'арбуз' = }")
# print(f"{'арбуз' < 'аршин' = }")
# print(f"{'ар' < 'аршин' = }")
# print(f"{'ар' < 'арбуз' = }")
# print(f"{'ар' < 'арбуз' = }")
# print(f"{'яблоко' < 'ёлка' = }")
# print(f"{'яблоко' < 'елка' = }")
# print(f"{'xx' in 'yoxxxyy'}")
# print(f"{'xyx' in 'yoxxxyy'}")
# print(f"{'люблю' in 'Я люблю жить!' = }")
# print(f"{'люблю' not in 'Я люблю жить!' = }")
# print(f"{' ' in 'Я люблю жить!' = }")
